rds:
  enabled: true
  regions:
    - "us-east-1"
vpc:
  enabled: true
  regions:
    - "us-east-1"
    - "eu-central-1"
    - "eu-west-1"
  timeout: 30s
route53:
  enabled: true
  region: "us-east-1"
  timeout: 300s
  interval: 300s
ec2:
  enabled: true
  regions:
    - "us-east-1"
    - "eu-central-1"
    - "us-west-1"
  timeout: 30s
