rds:
  enabled: false
  regions:
    - "us-east-1"
vpc:
  enabled: false
  regions:
    - "us-east-1"
    - "eu-central-1"
    - "eu-central-2"
  timeout: 30s
route53:
  enabled: false
  region: "us-east-1"
  timeout: 60s
ec2:
  enabled: true
  regions:
    - "us-east-1"
    - "eu-central-1"
    - "us-west-1"
  timeout: 30s
