// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/iam.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	aws "github.com/aws/aws-sdk-go/aws"
	request "github.com/aws/aws-sdk-go/aws/request"
	iam "github.com/aws/aws-sdk-go/service/iam"
	servicequotas "github.com/aws/aws-sdk-go/service/servicequotas"
	gomock "github.com/golang/mock/gomock"
)

// MockIAMClient is a mock of IAMClient interface.
type MockIAMClient struct {
	ctrl     *gomock.Controller
	recorder *MockIAMClientMockRecorder
}

// MockIAMClientMockRecorder is the mock recorder for MockIAMClient.
type MockIAMClientMockRecorder struct {
	mock *MockIAMClient
}

// NewMockIAMClient creates a new mock instance.
func NewMockIAMClient(ctrl *gomock.Controller) *MockIAMClient {
	mock := &MockIAMClient{ctrl: ctrl}
	mock.recorder = &MockIAMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAMClient) EXPECT() *MockIAMClientMockRecorder {
	return m.recorder
}

// ListRolesPagesWithContext mocks base method.
func (m *MockIAMClient) ListRolesPagesWithContext(ctx aws.Context, input *iam.ListRolesInput, fn func(*iam.ListRolesOutput, bool) bool, opts ...request.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRolesPagesWithContext", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListRolesPagesWithContext indicates an expected call of ListRolesPagesWithContext.
func (mr *MockIAMClientMockRecorder) ListRolesPagesWithContext(ctx, input, fn interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolesPagesWithContext", reflect.TypeOf((*MockIAMClient)(nil).ListRolesPagesWithContext), varargs...)
}

// MockServiceQuotasClient is a mock of ServiceQuotasClient interface.
type MockServiceQuotasClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceQuotasClientMockRecorder
}

// MockServiceQuotasClientMockRecorder is the mock recorder for MockServiceQuotasClient.
type MockServiceQuotasClientMockRecorder struct {
	mock *MockServiceQuotasClient
}

// NewMockServiceQuotasClient creates a new mock instance.
func NewMockServiceQuotasClient(ctrl *gomock.Controller) *MockServiceQuotasClient {
	mock := &MockServiceQuotasClient{ctrl: ctrl}
	mock.recorder = &MockServiceQuotasClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceQuotasClient) EXPECT() *MockServiceQuotasClientMockRecorder {
	return m.recorder
}

// GetServiceQuotaWithContext mocks base method.
func (m *MockServiceQuotasClient) GetServiceQuotaWithContext(ctx aws.Context, input *servicequotas.GetServiceQuotaInput, opts ...request.Option) (*servicequotas.GetServiceQuotaOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceQuotaWithContext", varargs...)
	ret0, _ := ret[0].(*servicequotas.GetServiceQuotaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceQuotaWithContext indicates an expected call of GetServiceQuotaWithContext.
func (mr *MockServiceQuotasClientMockRecorder) GetServiceQuotaWithContext(ctx, input interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceQuotaWithContext", reflect.TypeOf((*MockServiceQuotasClient)(nil).GetServiceQuotaWithContext), varargs...)
}
