// Code generated by MockGen. DO NOT EDIT.
// Source: ./awsclient.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	types "github.com/aws/aws-sdk-go-v2/service/elasticache/types"
	iam "github.com/aws/aws-sdk-go-v2/service/iam"
	types0 "github.com/aws/aws-sdk-go-v2/service/kafka/types"
	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	types1 "github.com/aws/aws-sdk-go-v2/service/rds/types"
	route53 "github.com/aws/aws-sdk-go-v2/service/route53"
	types2 "github.com/aws/aws-sdk-go-v2/service/route53/types"
	servicequotas "github.com/aws/aws-sdk-go-v2/service/servicequotas"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DescribeCacheClustersAll mocks base method.
func (m *MockClient) DescribeCacheClustersAll(ctx context.Context) ([]types.CacheCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeCacheClustersAll", ctx)
	ret0, _ := ret[0].([]types.CacheCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeCacheClustersAll indicates an expected call of DescribeCacheClustersAll.
func (mr *MockClientMockRecorder) DescribeCacheClustersAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeCacheClustersAll", reflect.TypeOf((*MockClient)(nil).DescribeCacheClustersAll), ctx)
}

// DescribeDBInstancesAll mocks base method.
func (m *MockClient) DescribeDBInstancesAll(ctx context.Context) ([]types1.DBInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDBInstancesAll", ctx)
	ret0, _ := ret[0].([]types1.DBInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBInstancesAll indicates an expected call of DescribeDBInstancesAll.
func (mr *MockClientMockRecorder) DescribeDBInstancesAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBInstancesAll", reflect.TypeOf((*MockClient)(nil).DescribeDBInstancesAll), ctx)
}

// DescribeDBLogFilesAll mocks base method.
func (m *MockClient) DescribeDBLogFilesAll(ctx context.Context, instanceId string) ([]*rds.DescribeDBLogFilesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDBLogFilesAll", ctx, instanceId)
	ret0, _ := ret[0].([]*rds.DescribeDBLogFilesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBLogFilesAll indicates an expected call of DescribeDBLogFilesAll.
func (mr *MockClientMockRecorder) DescribeDBLogFilesAll(ctx, instanceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBLogFilesAll", reflect.TypeOf((*MockClient)(nil).DescribeDBLogFilesAll), ctx, instanceId)
}

// DescribePendingMaintenanceActionsAll mocks base method.
func (m *MockClient) DescribePendingMaintenanceActionsAll(ctx context.Context) ([]types1.ResourcePendingMaintenanceActions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribePendingMaintenanceActionsAll", ctx)
	ret0, _ := ret[0].([]types1.ResourcePendingMaintenanceActions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribePendingMaintenanceActionsAll indicates an expected call of DescribePendingMaintenanceActionsAll.
func (mr *MockClientMockRecorder) DescribePendingMaintenanceActionsAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribePendingMaintenanceActionsAll", reflect.TypeOf((*MockClient)(nil).DescribePendingMaintenanceActionsAll), ctx)
}

// GetAccountSummary mocks base method.
func (m *MockClient) GetAccountSummary(ctx context.Context, input *iam.GetAccountSummaryInput, optFns ...func(*iam.Options)) (*iam.GetAccountSummaryOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountSummary", varargs...)
	ret0, _ := ret[0].(*iam.GetAccountSummaryOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSummary indicates an expected call of GetAccountSummary.
func (mr *MockClientMockRecorder) GetAccountSummary(ctx, input interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSummary", reflect.TypeOf((*MockClient)(nil).GetAccountSummary), varargs...)
}

// GetHostedZoneLimit mocks base method.
func (m *MockClient) GetHostedZoneLimit(ctx context.Context, input *route53.GetHostedZoneLimitInput, optFns ...func(*route53.Options)) (*route53.GetHostedZoneLimitOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHostedZoneLimit", varargs...)
	ret0, _ := ret[0].(*route53.GetHostedZoneLimitOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostedZoneLimit indicates an expected call of GetHostedZoneLimit.
func (mr *MockClientMockRecorder) GetHostedZoneLimit(ctx, input interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostedZoneLimit", reflect.TypeOf((*MockClient)(nil).GetHostedZoneLimit), varargs...)
}

// GetServiceQuota mocks base method.
func (m *MockClient) GetServiceQuota(ctx context.Context, input *servicequotas.GetServiceQuotaInput, optFns ...func(*servicequotas.Options)) (*servicequotas.GetServiceQuotaOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceQuota", varargs...)
	ret0, _ := ret[0].(*servicequotas.GetServiceQuotaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceQuota indicates an expected call of GetServiceQuota.
func (mr *MockClientMockRecorder) GetServiceQuota(ctx, input interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceQuota", reflect.TypeOf((*MockClient)(nil).GetServiceQuota), varargs...)
}

// GetTransitGatewaysCount mocks base method.
func (m *MockClient) GetTransitGatewaysCount(ctx context.Context, input *ec2.DescribeTransitGatewaysInput) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransitGatewaysCount", ctx, input)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransitGatewaysCount indicates an expected call of GetTransitGatewaysCount.
func (mr *MockClientMockRecorder) GetTransitGatewaysCount(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransitGatewaysCount", reflect.TypeOf((*MockClient)(nil).GetTransitGatewaysCount), ctx, input)
}

// ListClustersAll mocks base method.
func (m *MockClient) ListClustersAll(ctx context.Context) ([]types0.ClusterInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClustersAll", ctx)
	ret0, _ := ret[0].([]types0.ClusterInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersAll indicates an expected call of ListClustersAll.
func (mr *MockClientMockRecorder) ListClustersAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersAll", reflect.TypeOf((*MockClient)(nil).ListClustersAll), ctx)
}

// ListHostedZonesAll mocks base method.
func (m *MockClient) ListHostedZonesAll(ctx context.Context) ([]types2.HostedZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHostedZonesAll", ctx)
	ret0, _ := ret[0].([]types2.HostedZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHostedZonesAll indicates an expected call of ListHostedZonesAll.
func (mr *MockClientMockRecorder) ListHostedZonesAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHostedZonesAll", reflect.TypeOf((*MockClient)(nil).ListHostedZonesAll), ctx)
}
