{
 "title": "AWS Resource Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EOL Status Distribution of RDS Instances",
   "type": "bargauge",
   "description": "Shows the number of RDS Instances categorized by their End-of-Life (EOL) status.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_resources_exporter_rds_eol_info) by (eol_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Version and EOL Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "aws_resources_exporter_rds_eol_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS EOL Alerts",
   "type": "alertlist",
   "description": "List of all RDS EOL alerts currently firing",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 }
  },
  { "title": "MSK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "EOL Status Distribution of MSK Clusters",
   "type": "bargauge",
   "description": "Shows the number of MSK clusters categorized by their End-of-Life (EOL) status.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_resources_exporter_msk_eol_info) by (eol_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MSK Version and EOL Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "aws_resources_exporter_msk_eol_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MSK EOL Alerts",
   "type": "alertlist",
   "description": "List of all MSK EOL alerts currently firing",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 }
  },
  { "title": "ElastiCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "EOL Status Distribution of ElastiCache Clusters",
   "type": "bargauge",
   "description": "Shows the number of ElastiCache clusters categorized by their End-of-Life (EOL) status.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_resources_exporter_elasticache_eol_info) by (eol_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ElastiCache Version and EOL Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 33 },
   "targets": [
    {
     "expr": "aws_resources_exporter_elasticache_eol_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ElastiCache EOL Alerts",
   "type": "alertlist",
   "description": "List of all ElastiCache EOL alerts currently firing",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 }
  },
  { "title": "VPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "IPv4 Address Usage per Subnet",
   "type": "timeseries",
   "description": "Shows IPv4 address utilization per subnet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_resources_exporter_vpc_ipv4addressespersubnet_capacity",
     "legendFormat": "{{subnetid}} capacity"
    },
    {
     "expr": "aws_resources_exporter_vpc_ipv4addressespersubnet_usage",
     "legendFormat": "{{subnetid}} used"
    }
   ]
  },
  {
   "title": "Subnet IPv4 Utilization",
   "type": "table",
   "description": "Shows percentage utilization of IPv4 addresses per subnet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(aws_resources_exporter_vpc_ipv4addressespersubnet_usage / aws_resources_exporter_vpc_ipv4addressespersubnet_capacity) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Route53", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Route53",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "aws_resources_exporter_route53_recordsperhostedzone_quota",
     "legendFormat": "{{hostedzonename}}-quota"
    },
    {
     "expr": "aws_resources_exporter_route53_recordsperhostedzone_total",
     "legendFormat": "{{hostedzonename}}-total"
    }
   ]
  }
 ]
}