apiVersion: v1
kind: Template
metadata:
  name: aws-resource-exporter
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: aws-resource-exporter
    name: aws-resource-exporter
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: aws-resource-exporter
    template:
      metadata:
        labels:
          app: aws-resource-exporter
      spec:
        containers:
        - name: aws-resource-exporter
          image: ${IMAGE}:${IMAGE_TAG}
          ports:
          - containerPort: 9115
            name: http
            protocol: TCP
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: aws_secret_access_key
          - name: AWS_REGION
            value: ${AWS_REGION}
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 50Mi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: aws-resource-exporter
    name: aws-resource-exporter
  spec:
    selector:
      app: aws-resource-exporter
    ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
    type: ClusterIP
parameters:
- name: IMAGE
  value: quay.io/app-sre/aws-resource-exporter
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "1"
- name: SECRET_NAME
  value: aws-resource-exporter
- name: AWS_REGION
  value: us-east-1
