apiVersion: v1
kind: Template
metadata:
  name: aws-resource-exporter
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "multiple replicas is multiple cost"
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        serviceAccountName: ${NAME}
        containers:
        - name: aws-resource-exporter
          image: ${IMAGE}:${IMAGE_TAG}
          ports:
          - containerPort: 9115
            name: http
            protocol: TCP
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: aws_secret_access_key
          - name: AWS_REGION
            value: ${AWS_REGION}
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 50Mi
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            initialDelaySeconds: 10
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            initialDelaySeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
    type: ClusterIP
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  data:
    aws-resource-exporter-config.yaml: |
      default:
        regions: "us-east-1"
        timeout: 10s
      rds: {}
      vpc:
        regions: ""
        timeout: 30s
      route53:
        regions: ""
        timeout: 60s
parameters:
- name: NAME
  value: aws-resource-exporter
- name: IMAGE
  value: quay.io/app-sre/aws-resource-exporter
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "1"
- name: SECRET_NAME
  value: aws-resource-exporter
- name: AWS_REGION
  value: us-east-1
