apiVersion: v1
kind: Template
metadata:
  name: aws-resource-exporter
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "multiple replicas is multiple cost"
      ignore-check.kube-linter.io/unset-cpu-requirements: "no cpu limits"
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        serviceAccountName: ${NAME}
        volumes:
          - name: exporter-configuration
            configMap:
              name: ${CONFIGMAP_NAME}
        containers:
        - name: aws-resource-exporter
          image: ${IMAGE}:${IMAGE_TAG}
          ports:
          - containerPort: 9115
            name: http
            protocol: TCP
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: aws_secret_access_key
          - name: AWS_REGION
            value: ${AWS_REGION}
          - name: AWS_RESOURCE_EXPORTER_CONFIG_FILE
            value: /etc/aws-resource-exporter/aws-resource-exporter-config.yaml
          volumeMounts:
            - name: exporter-configuration
              mountPath: /etc/aws-resource-exporter/
          resources:
            limits:
              memory: ${MEMORY_LIMITS}
            requests:
              cpu: ${CPU_REQUESTS}
              memory: ${MEMORY_REQUESTS}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            initialDelaySeconds: 10
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            initialDelaySeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
    type: ClusterIP
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      qontract.recycle: "true"
    labels:
      app: ${NAME}
    name: ${CONFIGMAP_NAME}
  data:
    aws-resource-exporter-config.yaml: ${AWS_RESOURE_EXPORTER_CONFIGURATION}
parameters:
- name: NAME
  value: aws-resource-exporter
- name: IMAGE
  value: quay.io/app-sre/aws-resource-exporter
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "1"
- name: SECRET_NAME
  value: aws-resource-exporter
- name: AWS_REGION
  value: us-east-1
- name: CONFIGMAP_NAME
  value: aws-resource-exporter-config
- name: CPU_REQUESTS
  value: 50m
- name: MEMORY_LIMITS
  value: 150Mi
- name: MEMORY_REQUESTS
  value: 150Mi
- name: AWS_RESOURCE_EXPORTER_CONFIGURATION
  value: |
    default:
      regions: "us-east-1"
      timeout: 10s
    rds: {}
    vpc:
      regions: ""
      timeout: 30s
    route53:
      regions: ""
      timeout: 60s
